
package com.stfx.cli.sew.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Cef3", targetNamespace = "http://services.sew.cli.stfx.com/", wsdlLocation = "http://54.200.112.228:8080/SewWsdls/Cef3?wsdl")
public class Cef3_Service
    extends Service
{

    private final static URL CEF3_WSDL_LOCATION;
    private final static WebServiceException CEF3_EXCEPTION;
    private final static QName CEF3_QNAME = new QName("http://services.sew.cli.stfx.com/", "Cef3");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://54.200.112.228:8080/SewWsdls/Cef3?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CEF3_WSDL_LOCATION = url;
        CEF3_EXCEPTION = e;
    }

    public Cef3_Service() {
        super(__getWsdlLocation(), CEF3_QNAME);
    }

    public Cef3_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CEF3_QNAME, features);
    }

    public Cef3_Service(URL wsdlLocation) {
        super(wsdlLocation, CEF3_QNAME);
    }

    public Cef3_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CEF3_QNAME, features);
    }

    public Cef3_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Cef3_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Cef3
     */
    @WebEndpoint(name = "Cef3Port")
    public Cef3 getCef3Port() {
        return super.getPort(new QName("http://services.sew.cli.stfx.com/", "Cef3Port"), Cef3.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Cef3
     */
    @WebEndpoint(name = "Cef3Port")
    public Cef3 getCef3Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.sew.cli.stfx.com/", "Cef3Port"), Cef3.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CEF3_EXCEPTION!= null) {
            throw CEF3_EXCEPTION;
        }
        return CEF3_WSDL_LOCATION;
    }

}
