
package com.stfx.cli.sew.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Napa", targetNamespace = "http://services.sew.cli.stfx.com/", wsdlLocation = "http://54.200.112.228:8080/SewWsdls/Napa?wsdl")
public class Napa_Service
    extends Service
{

    private final static URL NAPA_WSDL_LOCATION;
    private final static WebServiceException NAPA_EXCEPTION;
    private final static QName NAPA_QNAME = new QName("http://services.sew.cli.stfx.com/", "Napa");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://54.200.112.228:8080/SewWsdls/Napa?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NAPA_WSDL_LOCATION = url;
        NAPA_EXCEPTION = e;
    }

    public Napa_Service() {
        super(__getWsdlLocation(), NAPA_QNAME);
    }

    public Napa_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), NAPA_QNAME, features);
    }

    public Napa_Service(URL wsdlLocation) {
        super(wsdlLocation, NAPA_QNAME);
    }

    public Napa_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NAPA_QNAME, features);
    }

    public Napa_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Napa_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Napa
     */
    @WebEndpoint(name = "NapaPort")
    public Napa getNapaPort() {
        return super.getPort(new QName("http://services.sew.cli.stfx.com/", "NapaPort"), Napa.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Napa
     */
    @WebEndpoint(name = "NapaPort")
    public Napa getNapaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.sew.cli.stfx.com/", "NapaPort"), Napa.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NAPA_EXCEPTION!= null) {
            throw NAPA_EXCEPTION;
        }
        return NAPA_WSDL_LOCATION;
    }

}
